CREATE TABLE "Session" (
  "id" TEXT PRIMARY KEY, "shop" TEXT NOT NULL, "state" TEXT NOT NULL, "isOnline" BOOLEAN NOT NULL DEFAULT false,
  "scope" TEXT, "expires" TIMESTAMP(3), "accessToken" TEXT NOT NULL, "userId" BIGINT, "firstName" TEXT, "lastName" TEXT,
  "email" TEXT, "accountOwner" BOOLEAN NOT NULL DEFAULT false, "locale" TEXT, "collaborator" BOOLEAN DEFAULT false,
  "emailVerified" BOOLEAN DEFAULT false, "refreshToken" TEXT, "refreshTokenExpires" TIMESTAMP(3)
);
CREATE INDEX "Session_shop_idx" ON "Session"("shop");
CREATE TABLE "Shop" ("domain" TEXT PRIMARY KEY,"installedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"uninstalledAt" TIMESTAMP(3),"currencyCode" TEXT NOT NULL DEFAULT 'GBP',"timezone" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ShopSettings" ("id" TEXT PRIMARY KEY,"shopDomain" TEXT NOT NULL UNIQUE,"orderTag" TEXT NOT NULL DEFAULT 'personalised-upsell',"productionEmail" TEXT,"privacyContact" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ShopSettings_shopDomain_fkey" FOREIGN KEY("shopDomain") REFERENCES "Shop"("domain") ON DELETE CASCADE);
CREATE TABLE "Offer" ("id" TEXT PRIMARY KEY,"shopDomain" TEXT NOT NULL,"name" TEXT NOT NULL DEFAULT 'Personalised upsell',"status" TEXT NOT NULL DEFAULT 'ACTIVE',"priority" INTEGER NOT NULL DEFAULT 100,"variantId" TEXT NOT NULL,"productId" TEXT,"productTitle" TEXT NOT NULL,"variantTitle" TEXT,"productImageUrl" TEXT,"currencyCode" TEXT NOT NULL DEFAULT 'GBP',"originalPrice" DECIMAL(12,2) NOT NULL,"discountType" TEXT NOT NULL DEFAULT 'percentage',"discountValue" DECIMAL(12,2) NOT NULL DEFAULT 15,"headline" TEXT NOT NULL DEFAULT 'Add a personalised extra',"description" TEXT NOT NULL DEFAULT 'Personalise this item and add it to your order in one click.',"buttonLabel" TEXT NOT NULL DEFAULT 'Add personalised item',"triggerMode" TEXT NOT NULL DEFAULT 'ALWAYS',"triggerConfig" JSONB,"metafieldNamespace" TEXT NOT NULL DEFAULT 'personalised_upsell',"metafieldKey" TEXT NOT NULL DEFAULT 'details',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Offer_shopDomain_fkey" FOREIGN KEY("shopDomain") REFERENCES "Shop"("domain") ON DELETE CASCADE);
CREATE INDEX "Offer_shopDomain_status_priority_idx" ON "Offer"("shopDomain","status","priority");
CREATE TABLE "PersonalisationField" ("id" TEXT PRIMARY KEY,"offerId" TEXT NOT NULL,"key" TEXT NOT NULL,"type" TEXT NOT NULL DEFAULT 'TEXT',"label" TEXT NOT NULL,"placeholder" TEXT,"helpText" TEXT,"required" BOOLEAN NOT NULL DEFAULT false,"minLength" INTEGER,"maxLength" INTEGER,"options" JSONB,"sortOrder" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PersonalisationField_offerId_fkey" FOREIGN KEY("offerId") REFERENCES "Offer"("id") ON DELETE CASCADE,CONSTRAINT "PersonalisationField_offerId_key_key" UNIQUE("offerId","key"));
CREATE INDEX "PersonalisationField_offerId_sortOrder_idx" ON "PersonalisationField"("offerId","sortOrder");
CREATE TABLE "Acceptance" ("id" TEXT PRIMARY KEY,"shopDomain" TEXT NOT NULL,"referenceId" TEXT NOT NULL,"offerId" TEXT NOT NULL,"variantId" TEXT NOT NULL,"personalisation" JSONB NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"orderId" TEXT,"orderName" TEXT,"errorMessage" TEXT,"appliedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Acceptance_shopDomain_fkey" FOREIGN KEY("shopDomain") REFERENCES "Shop"("domain") ON DELETE CASCADE,CONSTRAINT "Acceptance_offerId_fkey" FOREIGN KEY("offerId") REFERENCES "Offer"("id") ON DELETE CASCADE,CONSTRAINT "Acceptance_shopDomain_referenceId_offerId_key" UNIQUE("shopDomain","referenceId","offerId"));
CREATE INDEX "Acceptance_shopDomain_status_createdAt_idx" ON "Acceptance"("shopDomain","status","createdAt"); CREATE INDEX "Acceptance_orderId_idx" ON "Acceptance"("orderId");
CREATE TABLE "AnalyticsEvent" ("id" TEXT PRIMARY KEY,"shopDomain" TEXT NOT NULL,"offerId" TEXT,"type" TEXT NOT NULL,"referenceId" TEXT,"revenue" DECIMAL(12,2),"currencyCode" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AnalyticsEvent_shopDomain_fkey" FOREIGN KEY("shopDomain") REFERENCES "Shop"("domain") ON DELETE CASCADE,CONSTRAINT "AnalyticsEvent_offerId_fkey" FOREIGN KEY("offerId") REFERENCES "Offer"("id") ON DELETE SET NULL);
CREATE INDEX "AnalyticsEvent_shopDomain_type_createdAt_idx" ON "AnalyticsEvent"("shopDomain","type","createdAt"); CREATE INDEX "AnalyticsEvent_offerId_type_createdAt_idx" ON "AnalyticsEvent"("offerId","type","createdAt");
